"""Generic investigative-result export (JSON + PDF).

Data-driven, so any result dict (person, fingerprint, ...) renders without a
per-type template. Matches the soc-toolkit JSON envelope; PDF via WeasyPrint.
The investigative results aren't tabular, so CSV is intentionally omitted.
"""
from __future__ import annotations

import io
import json
from datetime import UTC, datetime

from jinja2 import Template
from weasyprint import HTML

_PDF_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
    body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a1a1a; }
    h1 { color: #0d9488; border-bottom: 3px solid #0d9488; padding-bottom: 10px; }
    h2 { color: #0f766e; margin-top: 28px; font-size: 16px; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    th { background: #ccfbf1; padding: 8px; text-align: left; border: 1px solid #99f6e4; }
    td { padding: 7px 9px; border: 1px solid #e0e0e0; vertical-align: top;
         word-break: break-word; }
    tr:nth-child(even) { background: #fafafa; }
    ul { margin: 8px 0; }
    .footer { margin-top: 36px; padding-top: 14px; border-top: 1px solid #ccc;
              font-size: 11px; color: #666; }
</style>
</head>
<body>
    <h1>OSINT Toolkit - {{ report_type | title }} Report</h1>
    <p><strong>Generated:</strong> {{ timestamp }}</p>
    {% for key, value in data.items() %}
    <h2>{{ key | replace('_', ' ') | title }}</h2>
    {% if value is mapping %}
        <table>
        {% for k, v in value.items() %}
            <tr><th>{{ k | replace('_', ' ') | title }}</th><td>{{ v }}</td></tr>
        {% endfor %}
        </table>
    {% elif value is sequence and value is not string %}
        {% if value and value[0] is mapping %}
        <table>
            <tr>{% for col in value[0].keys() %}
                <th>{{ col | replace('_', ' ') | title }}</th>{% endfor %}</tr>
            {% for row in value %}
            <tr>{% for col in value[0].keys() %}
                <td>{{ row.get(col, '') }}</td>{% endfor %}</tr>
            {% endfor %}
        </table>
        {% else %}
        <ul>{% for item in value %}<li>{{ item }}</li>{% endfor %}</ul>
        {% endif %}
    {% else %}
        <p>{{ value }}</p>
    {% endif %}
    {% endfor %}
    <div class="footer">
        Generated by OSINT Toolkit | Nicholas Arcari | {{ timestamp }}
    </div>
</body>
</html>
"""


async def export_json(data: dict, report_type: str) -> io.BytesIO:
    output = {"report_type": report_type, "data": data}
    content = json.dumps(output, indent=2, default=str)
    return io.BytesIO(content.encode("utf-8"))


async def export_pdf(data: dict, report_type: str) -> io.BytesIO:
    html = Template(_PDF_TEMPLATE).render(
        report_type=report_type,
        data=data,
        timestamp=datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC"),
    )
    return io.BytesIO(HTML(string=html).write_pdf())
