import io
from datetime import UTC, datetime

from jinja2 import Template
from weasyprint import HTML

PDF_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
    body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a1a1a; }
    h1 { color: #0d47a1; border-bottom: 3px solid #0d47a1; padding-bottom: 10px; }
    h2 { color: #1565c0; margin-top: 30px; }
    .header { display: flex; justify-content: space-between; align-items: center; }
    .badge {
        padding: 4px 12px; border-radius: 4px; color: white;
        font-weight: bold; font-size: 12px;
    }
    .critical { background: #b71c1c; }
    .high { background: #e65100; }
    .medium { background: #f57f17; }
    .low { background: #1b5e20; }
    .info { background: #0d47a1; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th { background: #e3f2fd; padding: 10px; text-align: left; border: 1px solid #bbdefb; }
    td { padding: 8px 10px; border: 1px solid #e0e0e0; }
    tr:nth-child(even) { background: #fafafa; }
    .verdict {
        font-size: 24px; font-weight: bold; padding: 15px;
        text-align: center; border-radius: 8px;
    }
    .verdict-malicious { background: #ffcdd2; color: #b71c1c; }
    .verdict-suspicious { background: #fff3e0; color: #e65100; }
    .verdict-clean { background: #e8f5e9; color: #1b5e20; }
    .footer {
        margin-top: 40px; padding-top: 15px;
        border-top: 1px solid #ccc; font-size: 11px; color: #666;
    }
    .summary { background: #f5f5f5; padding: 15px; border-radius: 8px; margin: 15px 0; }
</style>
</head>
<body>
    <div class="header">
        <h1>SOC Toolkit - {{ report_type | title }} Report</h1>
    </div>
    <p><strong>Generated:</strong> {{ timestamp }}</p>

    {% if report_type == 'phishing' %}
        {% set verdict_class = data.verdict | lower
            if data.verdict in ['malicious', 'suspicious', 'clean']
            else 'suspicious' %}
        <div class="verdict verdict-{{ verdict_class }}">
            Verdict: {{ data.verdict }} (Risk Score: {{ data.risk_score }}/100)
        </div>

        <h2>Indicators</h2>
        <ul>
        {% for indicator in data.get('indicators', []) %}
            <li>{{ indicator }}</li>
        {% endfor %}
        </ul>

        <h2>Recommendations</h2>
        <ul>
        {% for rec in data.get('recommendations', []) %}
            <li>{{ rec }}</li>
        {% endfor %}
        </ul>

    {% elif report_type == 'logs' %}
        <div class="summary">{{ data.get('summary', '') }}</div>

        <h2>Alerts</h2>
        <table>
            <tr><th>Severity</th><th>Message</th><th>Source IP</th><th>MITRE</th></tr>
            {% for alert in data.get('alerts', []) %}
            <tr>
                <td><span class="badge {{ alert.severity }}">
                    {{ alert.severity | upper }}</span></td>
                <td>{{ alert.message }}</td>
                <td>{{ alert.source_ip or 'N/A' }}</td>
                <td>{{ alert.mitre_technique or '' }}</td>
            </tr>
            {% endfor %}
        </table>

    {% elif report_type == 'ioc' %}
        <div class="summary">Total IOCs extracted: {{ data.get('total_iocs', 0) }}</div>

        <h2>Indicators of Compromise</h2>
        <table>
            <tr><th>Type</th><th>Value</th><th>Malicious</th></tr>
            {% for ioc in data.get('iocs', []) %}
            <tr>
                <td>{{ ioc.type | upper }}</td>
                <td style="font-family: monospace;">{{ ioc.value }}</td>
                <td>
                    {{ 'Yes' if ioc.malicious else 'No' if ioc.malicious == false else 'Unknown' }}
                </td>
            </tr>
            {% endfor %}
        </table>
    {% endif %}

    <div class="footer">
        Generated by SOC Toolkit v0.1.0 | Nicholas Arcari | {{ timestamp }}
    </div>
</body>
</html>
"""


async def export_pdf(data: dict, report_type: str) -> io.BytesIO:
    """Export analysis results as a professional PDF report."""
    template = Template(PDF_TEMPLATE)
    html_content = template.render(
        report_type=report_type,
        data=data,
        timestamp=datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC"),
    )

    pdf_bytes = HTML(string=html_content).write_pdf()
    return io.BytesIO(pdf_bytes)