"""subdomain_unique_constraint

Revision ID: 31a5b85df782
Revises: 536122f7b32f
Create Date: 2026-04-22 12:07:20.885043

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401 - kept for future autogenerated diffs
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31a5b85df782"
down_revision: str | None = "536122f7b32f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # SQLite doesn't support ALTER TABLE ADD CONSTRAINT; Alembic's batch
    # mode emulates it via the copy-and-move strategy. Use batch on every
    # dialect so this migration works unchanged on SQLite and Postgres.
    with op.batch_alter_table("subdomains") as batch_op:
        batch_op.create_unique_constraint(
            "uq_subdomains_target_fqdn", ["target_id", "fqdn"]
        )


def downgrade() -> None:
    with op.batch_alter_table("subdomains") as batch_op:
        batch_op.drop_constraint("uq_subdomains_target_fqdn", type_="unique")
